const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{can_dash: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Hero: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{Keyboard: 0},
	{TiledBackground3: 0},
	{Group: 0},
	{DeathPit: 0},
	{Sprite2: 0},
	{Group2: 0},
	{right: 0},
	{Pathfinding: 0},
	{Enemy: 0},
	{Sprite: 0},
	{TiledBackground5: 0},
	{Sprite3: 0},
	{TiledBackground4: 0},
	{Sprite4: 0},
	{TiledBackground6: 0},
	{Sprite5: 0},
	{Button: 0},
	{Group3: 0},
	{Sprite6: 0},
	{Mouse: 0},
	{Group4: 0},
	{TiledBackground7: 0},
	{Sprite7: 0},
	{Sprite8: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Hero: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Group: class extends self.ISpriteInstance {},
	DeathPit: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Group3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Group4: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}